import Link from "next/link";
import { AlertCircle, ArrowRight, CreditCard, FileText, GraduationCap, Upload } from "lucide-react";
import { Header } from "@/components/Header";
import { requireProfile } from "@/lib/auth/currentUser";
import { getCustomerDashboardData } from "@/lib/queries/dashboard";
import { syncStudentAlerts } from "@/lib/student/alerts";

export default async function PendingPage() {
  const { user, profile } = await requireProfile();
  await syncStudentAlerts(profile.id);
  const data = await getCustomerDashboardData(user.id);
  if (!data) return null;
  const checklistItems = data.openChecklistItems.slice(0, 30);
  const pendingDocs = data.documents.filter((doc) => ["PENDING_REVIEW","MORE_INFO_REQUIRED"].includes(doc.reviewStatus));
  const total = checklistItems.length + data.pendingPayments.length + data.pendingApplicationFees.length + pendingDocs.length;
  return <div className="min-h-screen bg-paper"><Header signedIn/><main className="mx-auto max-w-5xl px-5 py-8 sm:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-semibold text-ink">Pending</h1><p className="mt-2 text-sm text-mute">One place for everything waiting on you, SOUP or a payment.</p></div><div className="rounded-xl border border-hair bg-white px-4 py-2 text-sm font-semibold text-ink">{total} open</div></div>
  <section className="mt-6 grid gap-4 lg:grid-cols-2">
    <div className="rounded-2xl border border-hair bg-white p-5"><div className="flex items-center gap-2 text-sm font-semibold text-ink"><GraduationCap size={16} className="text-teal"/> Application & journey actions</div><div className="mt-4 divide-y divide-hair">{checklistItems.length===0?<p className="py-5 text-xs text-mute">No journey actions are waiting right now.</p>:checklistItems.map((item)=><Link key={item.id} href="/journey" className="flex items-center justify-between gap-3 py-3"><div><div className="text-xs font-semibold text-ink">{item.title}</div><div className="mt-1 text-[11px] text-mute">{item.status.replaceAll("_"," ")}{item.dueAt?` · Due ${item.dueAt.toLocaleDateString()}`:""}</div></div><ArrowRight size={13} className="text-mute"/></Link>)}</div></div>
    <div className="rounded-2xl border border-hair bg-white p-5"><div className="flex items-center gap-2 text-sm font-semibold text-ink"><CreditCard size={16} className="text-teal"/> Payments</div><div className="mt-4 divide-y divide-hair">{data.pendingPayments.length+data.pendingApplicationFees.length===0?<p className="py-5 text-xs text-mute">No payments are waiting.</p>:<>{data.pendingPayments.map((p)=><Link key={p.id} href="/payments" className="flex items-center justify-between py-3"><div><div className="text-xs font-semibold text-ink">{p.title}</div><div className="mt-1 text-[11px] text-mute">{p.status.replaceAll("_"," ")}</div></div><div className="text-xs font-semibold text-ink">${Number(p.amount).toFixed(2)}</div></Link>)}{data.pendingApplicationFees.map((a)=><Link key={a.id} href="/payments" className="flex items-center justify-between py-3"><div><div className="text-xs font-semibold text-ink">{a.university?.name || "University"} application fee</div><div className="mt-1 text-[11px] text-mute">{a.applicationFeeStatus.replaceAll("_"," ")}</div></div><div className="text-xs font-semibold text-ink">{a.applicationFeeAmount?`${a.applicationFeeCurrency||"USD"} ${Number(a.applicationFeeAmount).toFixed(2)}`:"TBC"}</div></Link>)}</>}</div></div>
    <div className="rounded-2xl border border-hair bg-white p-5"><div className="flex items-center gap-2 text-sm font-semibold text-ink"><Upload size={16} className="text-teal"/> Documents under review</div><div className="mt-4 divide-y divide-hair">{pendingDocs.length===0?<p className="py-5 text-xs text-mute">No uploaded documents are waiting for review.</p>:pendingDocs.map((doc)=><Link key={doc.id} href="/documents" className="flex items-center justify-between py-3"><div><div className="text-xs font-semibold text-ink">{doc.originalFileName || doc.documentType.replaceAll("_"," ")}</div><div className="mt-1 text-[11px] text-mute">{doc.reviewStatus.replaceAll("_"," ")}</div></div><FileText size={14} className="text-mute"/></Link>)}</div></div>
    <div className="rounded-2xl border border-hair bg-white p-5"><div className="flex items-center gap-2 text-sm font-semibold text-ink"><AlertCircle size={16} className="text-teal"/> Next recommended action</div><p className="mt-4 text-sm leading-6 text-ink">{data.studentCase?.nextAction || "Nothing urgent is waiting. Ask Noodles what your next best step should be."}</p><Link href="/counselor" className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-navy">Ask Noodles <ArrowRight size={13}/></Link></div>
  </section></main></div>;
}
