import { prisma } from "@/lib/prisma";
import { normalizeTestingDetails } from "@/lib/applications/coreProfile";

// The "My Colleges" merge logic: a requirement generated by
// prepareApplicationRequirements (see src/lib/applications/requirements.ts)
// can carry a structured quantifiableMetric (currently just
// ENGLISH_TEST_MIN — the concrete case the feature was scoped around).
// This compares that threshold against the student's saved core-profile
// test score (Section 5, /profile/testing) and either auto-completes the
// item (no student action needed) or leaves it open with an explicit
// below-threshold flag, rather than silently leaving it as a generic
// unchecked task either way.
//
// Called from two places: right after a checklist is generated/refreshed
// (so a brand-new checklist starts pre-reconciled), and after the student
// saves Testing & Requirements (so entering a score retroactively resolves
// or flags matching items on every one of their existing applications —
// genuine "fill once, reuse everywhere", not just at creation time).
export async function reconcileCoreProfileWithChecklist(profileId: string, checklistId?: string) {
  const studentCase = await prisma.studentCase.findUnique({ where: { profileId }, select: { testingDetails: true } });
  const testing = normalizeTestingDetails(studentCase?.testingDetails);
  const score = Number(testing.englishScore);
  const hasScore = testing.englishTestType !== "NONE_YET" && Number.isFinite(score) && score > 0;

  const items = await prisma.journeyChecklistItem.findMany({
    where: {
      checklist: { profileId, kind: "ADMISSION", ...(checklistId ? { id: checklistId } : {}) },
      status: { notIn: ["COMPLETE", "NOT_APPLICABLE"] },
    },
    select: { id: true, status: true, metadata: true },
  });

  for (const item of items) {
    const metadata = item.metadata && typeof item.metadata === "object" && !Array.isArray(item.metadata) ? item.metadata as Record<string, unknown> : {};
    if (metadata.quantifiableMetric !== "ENGLISH_TEST_MIN") continue;
    const minScore = Number(metadata.quantifiableMinScore);
    if (!Number.isFinite(minScore) || minScore <= 0) continue;
    const requiredTestType = String(metadata.quantifiableTestType || "");
    const sameTestType = !requiredTestType || requiredTestType === testing.englishTestType.toUpperCase();
    if (!hasScore || !sameTestType) continue;

    if (score >= minScore) {
      await prisma.journeyChecklistItem.update({
        where: { id: item.id },
        data: {
          status: "COMPLETE",
          completedAt: new Date(),
          metadata: { ...metadata, autoSatisfiedFromCoreProfile: true, belowThreshold: false, thresholdFlagMessage: null },
        },
      });
    } else {
      await prisma.journeyChecklistItem.update({
        where: { id: item.id },
        data: {
          metadata: {
            ...metadata,
            autoSatisfiedFromCoreProfile: false,
            belowThreshold: true,
            thresholdFlagMessage: `Your ${testing.englishTestType} ${testing.englishScore} is below this program's required ${minScore}${requiredTestType ? "" : " (test type not confirmed as matching)"}.`,
          },
        },
      });
    }
  }
}
