export const KNOWN_PARTNER_WEBSITES: Record<string, string> = {
  "Algebra University College Croatia": "https://www.algebra.hr/",
  "Arden University": "https://arden.ac.uk/",
  "Arizona State University": "https://www.asu.edu/",
  "Berlin School of Business and Innovation": "https://www.berlinsbi.com/",
  "Bournemouth University": "https://www.bournemouth.ac.uk/",
  "Collegium Da Vinci Poland": "https://cdv.pl/",
  "Deakin University": "https://www.deakin.edu.au/",
  "Dublin Business School": "https://www.dbs.ie/",
  "ESDES Business School": "https://www.esdes.fr/",
  "ESDES University": "https://www.esdes.fr/",
  "GISMA University for Applied Sciences": "https://www.gisma.com/",
  "Griffith University": "https://www.griffith.edu.au/",
  "Higher Institute of Economics & Innovation WSEI Poland": "https://www.wsei.eu/",
  "Hochschule Fresenius": "https://www.hs-fresenius.com/",
  "International Business School Budapest": "https://www.ibs-b.hu/",
  "KEDGE Business School": "https://kedge.edu/",
  "La Trobe College": "https://www.latrobecollegeaustralia.edu.au/",
  "La Trobe College Australia": "https://www.latrobecollegeaustralia.edu.au/",
  "La Trobe University": "https://www.latrobe.edu.au/",
  "Northeastern University": "https://www.northeastern.edu/",
  "University at Buffalo": "https://www.buffalo.edu/",
  "University of Arizona": "https://www.arizona.edu/",
  "University of Debrecen": "https://edu.unideb.hu/",
  "University of Edinburgh": "https://www.ed.ac.uk/",
  "University of Europe for Applied Sciences": "https://www.ue-germany.com/",
  "University of Greenwich": "https://www.gre.ac.uk/",
  "Hellenic Sun Insurance Brokers / insuremart": "https://insuremart.pk/",
  "MCB Islamic Bank": "https://www.mcbislamicbank.com/",
  "LearnersDen.eu": "https://learnersden.eu/",
  "AHZ": "https://www.ahzassociates.com/",
  "ApplyBoard": "https://www.applyboard.com/",
  "GUS": "https://www.globaluniversitysystems.com/",
  "GUS / InUni": "https://www.globaluniversitysystems.com/network/partners",
  "IEO": "https://events.educationireland.net/",
  "ABN Global": "https://www.abnglobal.com/",
  "ConnectedHE": "https://connectedhe.com/",
  "EEUA": "https://www.eeca.university/",
};

export function knownPartnerWebsite(name: string) {
  return KNOWN_PARTNER_WEBSITES[name] || null;
}
