import Link from "next/link";
import { Download, GraduationCap } from "lucide-react";
import { Header } from "@/components/Header";
import { requireProfile } from "@/lib/auth/currentUser";
import { prisma } from "@/lib/prisma";

export default async function PlansPage() {
  const { profile } = await requireProfile();
  const plans = await prisma.universityShortlist.findMany({ where: { profileId: profile.id }, orderBy: { generatedAt: "desc" }, include: { _count: { select: { items: true } } } });
  return <div className="min-h-screen bg-paper"><Header signedIn/><main className="mx-auto max-w-5xl px-5 py-8 sm:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="text-xs font-semibold uppercase tracking-[.16em] text-teal">My SOUP</div><h1 className="mt-1 text-2xl font-semibold text-ink">University Application Plans</h1><p className="mt-2 text-sm text-mute">Every Counselor-generated shortlist is versioned and stays in your account.</p></div><Link href="/counselor?intent=universities" className="rounded-xl bg-navy px-4 py-2.5 text-sm font-semibold text-white">Talk to Counselor</Link></div><div className="mt-6 space-y-3">{plans.length === 0 ? <div className="rounded-2xl border border-hair bg-white p-6 text-sm text-mute">No saved application plans yet. Ask the Counselor to help you find universities first.</div> : plans.map((plan) => <div key={plan.id} className="rounded-2xl border border-hair bg-white p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><div className="rounded-xl bg-[#EAF0F5] p-2.5 text-navy"><GraduationCap size={16}/></div><div><div className="text-sm font-semibold text-ink">{plan.title}</div><div className="mt-1 text-xs text-mute">Version {plan.version} · {plan._count.items} university option{plan._count.items === 1 ? "" : "s"} · {plan.regionScope || "Search scope from Counselor"}</div><div className="mt-1 text-[11px] text-mute">Generated {plan.generatedAt.toLocaleDateString()}</div></div></div><div className="flex gap-2"><Link href={`/plans/${plan.id}`} className="rounded-xl border border-hair px-3 py-2 text-xs font-semibold text-ink">View plan</Link><a href={`/api/export/application-plan?id=${encodeURIComponent(plan.id)}`} className="inline-flex items-center gap-1 rounded-xl border border-teal px-3 py-2 text-xs font-semibold text-teal"><Download size={12}/> PDF</a></div></div></div>)}</div></main></div>;
}
